Change CMAKE_CXX_STANDARD from 11 to 14
I was getting the following error when trying to compile and install:
/home/mateus/Latte-Dock/app/iconitem.cpp: In member function ‘void Latte::IconItem::setSource(const QVariant&)’:
/home/mateus/Latte-Dock/app/iconitem.cpp:98:29: error: ‘make_unique’ is not a member of ‘std’
                 m_svgIcon = std::make_unique<Plasma::Svg>(this);

So, changing the CMAKE_CXX_STANDARD from 11 to 14 solved this, since make_unique is a C++14 feature.