Fix build on FreeBSD by including <array>.
Summary:
latte-dock-0.8.0/app/dock/dockview.h:367:44:
    error: implicit instantiation of undefined template 'std::__1::array<QMetaObject::Connection, 4>'
    std::array<QMetaObject::Connection, 4> connectionsManagedLayout;
                                           ^

Reviewers: #freebsd, mvourlakos, davidedmundson

Reviewed By: davidedmundson

Subscribers: plasma-devel

Tags: #plasma

Differential Revision: https://phabricator.kde.org/D14534

(cherry picked from commit 156accc34f4470c6a7f984a5ffec19586c1383b7)