Include necessary header file for std::abs
While compiling Latte-Dock, i got the following error:

/data/latte-dock/src/latte-dock-git/app/iconitem.cpp:393:46:   required from here
/data/latte-dock/src/latte-dock-git/app/../liblattedock/extras.h:69:20: error: call of overloaded ‘abs(double)’ is ambiguous
     return std::abs(x - y) < std::numeric_limits<T>::epsilon() *
     std::abs(x + y) * ulp

In order to solve this error, i have to include `cmath`.